Add badges
constata-eu/constata pull request #17
Opened 2023-03-17 18:49 UTC by LuchoLeonel

Fixes #16

2023-03-20 10:58 UTC, nubis requested changes
I'm thinking maybe, since there were no real uses of invitations, we can make a DB migration changing everywhere "INVITATION" was stored in the DB for "BADGE", and reinterpret every previous invitation as if it was a badge.
For the few actual testing invitations we've sent the entries have already been created, along with their templates which maintain whatever schema invitations had at the time.
If you find anything else that may conflict, we can talk about but ideally we get rid of any mention to invitations we may have in the code.

2023-03-20 10:58 UTC, nubis commented on constata_lib/src/models/download_proof_link.rs
> +          TemplateKind:: Badge => i18n::t!(l, public_certificate_share_text_badge),
We can drop Invitations here, and just use the badges text.

2023-03-20 14:39 UTC, nubis requested changes

2023-03-27 14:50 UTC, nubis approved these changes

2023-03-27 15:13 UTC, nubis submitted a review, later dismissed

2023-03-27 15:15 UTC, nubis commented on i18n/src/translations.rs
>    pub template_message_for_invitation: &'static str,
We don't need texts for invitations anymore.

2023-03-27 19:13 UTC, bronxi47 approved these changes

2023-03-29 14:02 UTC, merged